### ISSUE TITLE
International dateline

### ISSUE THREAD

**Issue by aredwood** [willymaps/spoke#1]
![image](https://user-images.githubusercontent.com/8777530/173352923-4bf58301-cfd0-421c-8cda-d481360f52af.png)

Got some weird behavior around the date line, just an fyi.

cool vis though!

**Comment by willymaps** [comment]
Thanks for opening! It was fixed here: https://github.com/willymaps/spoke/commit/2917520bac84a3490c42c2b230feef694e6edf5b
